### ISSUE TITLE
Error installing on Raspberry Pi

### ISSUE THREAD

**Issue by losttime** [natevw/pi-spi#14]
I get an error running `npm install pi-spi` on my Raspberry Pi (model B) running Raspbian.

Here's the error output
```
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/dcox/workspace/projects/rosie/node_modules/pi-spi/build'
  CXX(target) Release/obj.target/spi_binding/spi_binding.o
../spi_binding.cc:18:1: error: ‘uv_mutex_t’ does not name a type
../spi_binding.cc:23:5: error: ‘uv_work_t’ does not name a type
../spi_binding.cc:36:16: error: variable or field ‘_Transfer’ declared void
../spi_binding.cc:36:16: error: ‘uv_work_t’ was not declared in this scope
../spi_binding.cc:36:27: error: ‘req’ was not declared in this scope
spi_binding.target.mk:81: recipe for target 'Release/obj.target/spi_binding/spi_binding.o' failed
make: *** [Release/obj.target/spi_binding/spi_binding.o] Error 1
make: Leaving directory '/home/dcox/workspace/projects/rosie/node_modules/pi-spi/build'
```

Am I possibly missing some system dependencies?

**Comment by losttime** [comment]
I believe I have the dependencies for node-gyp, according to https://www.npmjs.com/package/node-gyp
```
$ python --version
Python 2.7.3
$ gcc --version
gcc (Debian 4.6.3-14+rpi1) 4.6.3
...
$ make --version
GNU Make 4.0
Built for arm-unknown-linux-gnueabihf
...
```

**Comment by natevw** [comment]
What version of node? This module likely only works with node 0.10.x at the moment and will need an update for newer versions of v8/libuv — sorry this is not specified via package.json engines.

I intend to update this (or happy for PR migrating it to use https://github.com/rvagg/nan instead of direct bindings) but haven't messed with the various options for node beyond v0.10 myself yet.

**Comment by losttime** [comment]
I see. I'm running 0.12.0.

**Comment by losttime** [comment]
I can confirm that it does install just fine with node 0.10.28. Thanks :)

**Comment by natevw** [comment]
Glad downgrading was an option for you! Hoping to update soon since 0.12 has been out for a while, just haven't quite dared update my main development machine to it and so it's been a bit off my radar.

**Comment by natevw** [comment]
I think I've fixed node 0.12.x compatibility with https://github.com/natevw/pi-spi/pull/15. (Will release once I can test on hardware…)

You can test via `npm install git://github.com/natevw/node-foreman.git#nan_compat` though if you're interested.

**Comment by natevw** [comment]
pi-spi@1.0.0 should be compatible with either version of node (and probably iojs too…)

**Comment by losttime** [comment]
Thanks for moving on this so quickly! :+1:

**Comment by adeptp** [comment]
running npm install pi-spi on my Raspberry Pi (model 2) running Raspbian:
 pi-spi@1.0.0 install /root/node_modules/pi-spi
> node-gyp rebuild

make: вход в каталог «/root/node_modules/pi-spi/build»
  CXX(target) Release/obj.target/spi_binding/spi_binding.o
In file included from ../spi_binding.cc:2:0:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../spi_binding.cc:2:
/root/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/root/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../spi_binding.cc:2:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), size)’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../spi_binding.cc: In member function ‘virtual void SpiTransfer::Execute()’:
../spi_binding.cc:72:19: warning: missing initializer for member ‘spi_ioc_transfer::rx_nbits’ [-Wmissing-field-initializers]
                   };
                   ^
../spi_binding.cc:72:19: warning: missing initializer for member ‘spi_ioc_transfer::pad’ [-Wmissing-field-initializers]
../spi_binding.cc: In member function ‘virtual void SpiTransfer::HandleOKCallback()’:
../spi_binding.cc:125:43: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /root/.node-gyp/4.0.0/include/node/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
             node::FatalException(try_catch);
                                           ^
In file included from ../spi_binding.cc:2:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:769:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
spi_binding.target.mk:88: ошибка выполнения рецепта для цели «Release/obj.target/spi_binding/spi_binding.o»
make: *** [Release/obj.target/spi_binding/spi_binding.o] Ошибка 1
make: выход из каталога «/root/node_modules/pi-spi/build»
gyp ERR! build error
